site_name: Social Media and Web Analytics Installation Guide
pages:
- Welcome: index.md
- Command Line Tools: commandLine.md
- Git: gitInstall.md
- R: r.md
- RStudio: rstudio.md
- R Packages: r-packages.md
- The Finish Line!: finish-line.md
- Contact Us: contact.md
- Citation & License: citation-license.md
- News & Updates: updates.md
- Acknowledgements: acknowledgement.md

theme: readthedocs
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
